### ISSUE TITLE
Problema NA voti in Abruzzo Camera

### ISSUE THREAD

**Issue by DavideMagno** [fbranda/elezioni-politiche-2022#5]
Ciao,

segnalo che c'è stato un problema di scraping per i voti dell'Abruzzo che sono NA per alcuni partiti

![Schermata 2022-09-28 alle 20 07 03](https://user-images.githubusercontent.com/9103832/192856790-da5e6cd3-b35b-438b-a9f7-d90b4408853c.png)

Saluti,
Davide

**Comment by fbranda** [comment]
Ciao Davide e grazie per la segnalazione. Il problema adesso dovrebbe essere risolto!

**Comment by DavideMagno** [comment]
Ottimo, grazie mille
