### ISSUE TITLE
Divisione per circoscrizioni

### ISSUE THREAD

**Issue by DavideMagno** [fbranda/elezioni-politiche-2022#6]
Salve, 

sarebbe possibile raggruppare per Circoscrizioni invece che per Regioni? Questo consentirebbe un ricalcolo dell'algoritmo del calcolo dei seggi

Queste ad esempio sono quelle della Camera:
![Schermata 2022-09-28 alle 20 23 11](https://user-images.githubusercontent.com/9103832/192860013-f8fcd4fa-e491-4ac1-9761-4c1ddb5113ab.png)

**Comment by fbranda** [comment]
Ho aggiunto il file richiesto!

**Comment by DavideMagno** [comment]
Ottimo, grazie mille
